World of Rigid Bodies (WoRB): mexFunction.cpp File Reference
mexFunction.cpp File Reference
The main entry point for the WoRB MATLAB function.
#include "WoRB.h"
#include "Utilities.h"
#include "WoRB_TestBed.h"
#include "mex.h"
#include "mexWoRB.h"
Data Structures
class WoRB_MexFunction
Represents WoRB test-bed that can be initialized from mexFunction arguments.
Functions
void mexFunction (int nArgOut, mxArray *argOut[], int nArgIn, const mxArray *argIn[])
The main entry routine for the MATLAB function WoRB.
Variables
static WoRB_MexFunction Application
static WoRB::GLUT_Framework
< WoRB_MexFunction > glut
Detailed Description
The main entry point for the WoRB MATLAB function.
Author:
Mikica Kocic
Version:
0.4
Date:
2012-05-14
Copyright:
GNU Public License.
Definition in file mexFunction.cpp.
Function Documentation
void mexFunction (int nArgOut, mxArray * argOut[], int nArgIn, const mxArray * argIn[])
The main entry routine for the MATLAB function WoRB.
Definition at line 310 of file mexFunction.cpp.
References WoRB::GLUT_Framework< GlutApplication >::Connect(), WoRB_MexFunction::CreateResultMatrix(), WoRB::GLUT_Framework< GlutApplication >::Disconnect(), WoRB_MexFunction::GetResult(), WoRB::GLUT_Framework< GlutApplication >::Initialize(), WoRB_MexFunction::Parse(), WoRB_TestBed::Run(), and WoRB_TestBed::SetupAnimation().
{
    if ( ! glut.Initialize () ) {
        return;
    }
    // Prevent clearing MEX-file from memory
    //
    if ( ! mexIsLocked () ) {
        mexLock ();
    }
    // Parse mexFunction input arguments
    //
    Application.Parse( nArgIn, argIn );
    //
    if ( nArgOut >= 1 ) {
        Application.CreateResultMatrix ();
    }
    Application.SetupAnimation ();
    glut.Connect( Application );
    Application.Run ();
    glut.Disconnect ();
    if ( nArgOut >= 1 ) {
        argOut[0] = Application.GetResult ();
    }
}
Variable Documentation
WoRB_MexFunction Application [static]
Definition at line 302 of file mexFunction.cpp.
WoRB::GLUT_Framework<WoRB_MexFunction> glut [static]
Definition at line 303 of file mexFunction.cpp.